---
title: "Introduction to AnimalGEILU"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to AnimalGEILU}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Introduction to AnimalGEILU

**AnimalGEILU** is an R package designed to calculate **greenhouse gas (GHG) emissions** and **land use** associated with livestock production.  

Currently supported animals:
- **Cattle**
- **Goat**
- **Sheep**

---

## What the Package Calculates


### Methane (CH₄) Emissions
- Enteric fermentation (from digestion)
- Manure management

### Nitrous Oxide (N₂O) Emissions
- Direct (from manure handling)
- Indirect (via volatilization and leaching)

### Land Use
- Associated with livestock feed production

---

## Installation

Install the package directly from GitHub using **remotes**:

- Install remotes if not already installed -> install.packages("remotes")

- Install AnimalGEILU from GitHub -> remotes::install_github("JuanCBM99/Animal_GEI_LU")

---

## Getting Started

Load the package and explore the default datasets:

library(AnimalGEILU)

---

## Next Steps

After familiarizing yourself with the package, move on to the Example Data vignette for detailed instructions on:

- Loading and exploring datasets

- Using your own data with templates

- Preparing data for calculations




