library(testthat)
library(herdr)
library(readr)
library(dplyr)

# 1. Helper updated to include ALL potential tags generated by the cattle model
setup_test_env <- function() {
  if (!dir.exists("user_data")) dir.create("user_data")

  # A. Census: Only the base mature animal
  write_csv(data.frame(
    animal_tag = "mature_dairy_cattle",
    region = "spain",
    subregion = "north",
    class_flex = "lactation",
    population = 1000
  ), "user_data/livestock_census.csv")

  # B. Definitions: MUST include the mature tag AND the generated offspring tags
  # If a tag is missing here, animal_type becomes NA and the test fails
  write_csv(data.frame(
    animal_tag = c("mature_dairy_cattle", "feedlot_calves_male",
                   "feedlot_calves_female", "dairy_calves_female_replacement",
                   "dairy_yearlings_female_replacement"),
    region = "spain",
    subregion = "north",
    class_flex = "lactation",
    animal_type = "cattle",
    animal_subtype = "dairy"
  ), "user_data/livestock_definitions.csv")

  # C. Parameters
  write_csv(data.frame(
    parameter = c("calving_rate", "replacement_rate"),
    animal_tag = c("mature_dairy_cattle", "mature_dairy_cattle"),
    value = c(0.9, 0.2)
  ), "user_data/reproduction_parameters.csv")
}

cleanup_test_env <- function() {
  if (dir.exists("user_data")) unlink("user_data", recursive = TRUE)
  if (dir.exists("output")) unlink("output", recursive = TRUE)
}

# --- TESTS ---

test_that("calculate_population processes automatic cycle for cattle", {
  setup_test_env()

  # Run orchestrator in automatic mode
  results <- calculate_population(automatic_cycle = TRUE, saveoutput = FALSE)

  # 1. Check that NAs were NOT produced in animal_type
  # This was the previous failure point
  types <- unique(results$animal_type)
  expect_false(any(is.na(types)))
  expect_equal(as.character(types), "cattle")

  # 2. Verify that offspring were actually created
  expect_true(any(grepl("calves", results$animal_tag)))

  cleanup_test_env()
})
