#' @importFrom utils globalVariables
utils::globalVariables(c(
  ".env", "A_val", "B0", "B_val", "C_preg_factor", "C_val", "EF3", "EF4", "EF5",
  "EF_CH4_kg_year", "Emissions_CH4_Mg_year",
  "Land_use_Total_m2", "Milk_yield_kg_day", "N2O_emissions",
  "NE_pregnancy", "NE_wool", "NE_work", "NEa", "NEg", "NEl", "NEm",
  "N_excreted", "N_intake", "N_leaching", "N_retention", "a", "adult_weight",
  "animal_category", "animal_subtype", "animal_type", "ash", "average_weight",
  "awms", "b", "beef_calves_female_replacement", "beef_calves_male_replacement",
  "c_pregnancy", "c_pregnancy_tag", "c_value", "ca", "ca_value", "category_share",
  "cfi", "cfi_value", "climate", "coefficient", "consumption_kg", "cp",
  "dairy_calves_female_replacement", "de", "de_percent", "de_safe", "description",
  "diet_tag", "dm_ingested_derived", "dry_matter_yield", "duration", "eb",
  "ef_kg_animal_year", "ef_value", "emissions_total", "fat_content", "frac_gas",
  "frac_leach", "ge", "region", "hours", "animal_tag", "ingredient",
  "ingredient_share", "ingredient_type", "land_use_m2_per_unit", "land_use_total",
  "management_duration", "management_system", "mature_beef_bull", "mature_beef_cattle",
  "mature_dairy_cattle", "mature_goat_female_dairy", "mature_goat_female_meat",
  "mature_goat_male_dairy", "mature_goat_male_meat", "mature_sheep_female_dairy",
  "mature_sheep_female_meat", "mature_sheep_male_dairy", "mature_sheep_male_meat",
  "mcf", "milk_yield", "milk_protein", "milk_share", "milk_replacer_share",
  "forage_share", "concentrate_share",
  "n2o_g", "n2o_l", "n_leaching_kg_year", "n_volatilization_kg_year", "ndf",
  "parameter", "pop_beef_calves_female", "pop_beef_calves_female_replacement",
  "pop_beef_calves_male", "pop_beef_calves_male_replacement",
  "pop_dairy_calves_female_replacement", "pop_feedlot_calves_female",
  "pop_feedlot_calves_male", "pop_kid_goat_female_dairy_replacement",
  "pop_kid_goat_female_meat_replacement", "pop_kid_goat_male_dairy_replacement",
  "pop_kid_goat_male_meat_replacement", "pop_lamb_dairy_slaughter",
  "pop_lamb_female_dairy_replacement", "pop_lamb_female_meat_replacement",
  "pop_lamb_male_dairy_replacement", "pop_lamb_male_meat_replacement",
  "pop_lamb_meat_slaughter", "population", "pr", "reg", "rem", "sex",
  "share_weight", "share_weight_factor", "system_base", "system_climate",
  "system_variant", "total_beef_births", "total_dairy_births", "total_meat_births",
  "total_alloc", "ue_factor", "value", "vs", "weight_factor", "weight_gain",
  "wool_yield", "ym", "subregion", "zone_parent", "class_flex",
  "CO2eq_enteric", "CO2eq_manure", "CO2eq_n2o", "CO2eq_Total_Gg",
  "Carbon_Footprint_m2", "ing_share_num", "yield_num",
  "CH4_enteric_Mg", "CH4_manure_Mg", "N2O_direct_kg", "N2O_vol_kg", "N2O_lea_kg"
))
