#' @importFrom utils globalVariables
utils::globalVariables(c(
  ".env", "A_val", "B0", "B_val", "C_preg_factor", "C_val", "EF5", "EF_CH4_kg_year",
  "Emissions_CH4_Mg_year", "Land_use_Total_m2", "Milk_yield_kg_day", "N2O_L",
  "N2O_emissions", "NE_pregnancy", "NE_wool", "NE_work", "NEa", "NEg", "NEl", "NEm",
  "N_excreted", "N_intake", "N_leaching", "N_retention", "a", "adult_weight",
  "animal_category", "animal_subtype", "animal_type", "ash", "average_weight",
  "awms", "b", "beef_calves_female_replacement", "beef_calves_male_replacement",
  "c_pregnancy", "c_pregnancy_tag", "c_value", "ca", "ca_value", "category_share",
  "cfi", "cfi_value", "climate", "coefficient", "consumption_kg", "cp",
  "dairy_calves_female_replacement", "de", "de_percent", "de_safe", "description",
  "diet_tag", "dm_ingested_total", "dry_matter_yield", "duration", "ef4",
  "ef_kg_animal_year", "ef_value", "emissions_total", "fat_content", "frac_gas_ms",
  "frac_leach_ms", "ge", "region", "hours", "animal_tag", "ingredient",
  "ingredient_share", "land_use_m2_per_unit", "land_use_total", "management_duration",
  "management_system", "mature_beef_bull", "mature_beef_cattle", "mature_dairy_cattle",
  "mature_goat_female_dairy", "mature_goat_female_meat", "mature_goat_male_dairy",
  "mature_goat_male_meat", "mature_sheep_female_dairy", "mature_sheep_female_meat",
  "mature_sheep_male_dairy", "mature_sheep_male_meat", "mcf", "milk_yield", "n2o_g",
  "n_volatilization", "ndf", "parameter", "pop_beef_calves_female",
  "pop_beef_calves_female_replacement", "pop_beef_calves_male",
  "pop_beef_calves_male_replacement", "pop_dairy_calves_female_replacement",
  "pop_feedlot_calves_female", "pop_feedlot_calves_male",
  "pop_kid_goat_female_dairy_replacement", "pop_kid_goat_female_meat_replacement",
  "pop_kid_goat_male_dairy_replacement", "pop_kid_goat_male_meat_replacement",
  "pop_lamb_dairy_slaughter", "pop_lamb_female_dairy_replacement",
  "pop_lamb_female_meat_replacement", "pop_lamb_male_dairy_replacement",
  "pop_lamb_male_meat_replacement", "pop_lamb_meat_slaughter", "population", "pr",
  "reg", "rem", "sex", "share_weight", "system_climate", "total_beef_births",
  "total_dairy_births", "total_meat_births", "ue_factor", "value", "vs",
  "weight_factor", "weight_gain", "wool_yield", "ym", "subregion", "zone_parent", "class_flex"
))
